[package]
name = "decompress-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }
decompress = { path = "../decompress" }
mimalloc = "0.1"
wheel = { git = "https://github.com/fenhl/wheel", default-features = false }
