[package]
name = "decompress-cli"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
decompress = { path = "../decompress" }
mimalloc = "0.1.44"
wheel = { git = "https://github.com/fenhl/wheel", default-features = false }
