[target.aarch64-pc-windows-msvc]
rustflags = [
    "-C", "target-feature=+crt-static", # to remove the runtime VS requirement
]

[target.i686-pc-windows-msvc]
rustflags = [
    "-C", "target-feature=+crt-static", # to remove the runtime VS requirement
]

[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "target-feature=+crt-static", # to remove the runtime VS requirement
]
